# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234070a78198adc1d3af1540c362e8c73bddc4b6f93a6b6041f6102e9ff6430586e9cc831aed23517b2536586787b59bf2b612d18d6362b4aa51250d82521d68

test:
  secret_key_base: a4a94632c3acb18381592186ded8b640ebfdf93ebb897cb5868b6f2a38efc8eff2ff4ffd394ceff7d8c0d9d9f79a2cde1c080f079a845c0d4b335bc86d8850e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
